const kHolidays = [
  "Sick leave",
  "Casual leave",
  "Maternity leave",
  "Paternity leave",
  "Bereavement leave",
  "Privilege leave",
  "Marriage leave",
  "Compensatory off",
  "Sabbatical leave",
  "Loss of pay",
  "Leave without pay",
  "LOP leave",
  "Public holidays",
  "Annual leave",
  "Study leave",
  "Childcare leave",
  "Christmas Day",
  "Easter",
  "Holi",
  "Independence Day",
  "Paid leave",
  "Paternity leaves",
  "Personal time off",
  "Quarantine leave",
  "Ramdan",
  "Bakrid"
];
